# our base image
FROM golang

#GO GET Needed packages
RUN go get "github.com/gorilla/mux"
RUN go get "gopkg.in/mgo.v2"
RUN go get "gopkg.in/mgo.v2/bson"
RUN go get "github.com/rs/xid"

ADD . /go/src/mr-boucher/angular-golang-mongodb-example

WORKDIR /go/src/mr-boucher/angular-golang-mongodb-example

RUN go build main.go

EXPOSE 8000

# run the application
CMD ["./main"]

